export interface CurrencyInfo {
  isoCode: string;
  symbol: string;
  name: string;
}

export interface CurrencyInfoItems {
  [key: string]: CurrencyInfo;
}

export const CurrencyMetadata: CurrencyInfoItems = {
  GBP: { isoCode: "GBP", symbol: "£", name: "British Pound" },
  EUR: { isoCode: "EUR", symbol: "€", name: "Euro" },
  USD: { isoCode: "USD", symbol: "$", name: "US Dollar" },

  AED: { "name": "United Arab Emirates Dirham", "isoCode": "AED", symbol: "د.إ" },
  AFN: { "name": "Afghan Afghani", "isoCode": "AFN", symbol: "؋" },
  ALL: { "name": "Albanian Lek", "isoCode": "ALL", symbol: "L" },
  AMD: { "name": "Armenian Dram", "isoCode": "AMD", symbol: "֏" },
  ANG: { "name": "Netherlands Antillean Guilder", "isoCode": "ANG", symbol: "ƒ" },
  AOA: { "name": "Angolan Kwanza", "isoCode": "AOA", symbol: "Kz" },
  ARS: { "name": "Argentine Peso", "isoCode": "ARS", symbol: "CLP$" },
  AUD: { "name": "Australian Dollar", "isoCode": "AUD", symbol: "$" },
  AWG: { "name": "Aruban Florin", "isoCode": "AWG", symbol: "ƒ" },
  AZN: { "name": "Azerbaijani Manat", "isoCode": "AZN", symbol: "₼" },
  BAM: {
    "name": "Bosnia-Herzegovina Convertible Mark",
    "isoCode": "BAM"
 , symbol: "KM" },
  BBD: { "name": "Barbadian Dollar", "isoCode": "BBD", symbol: "Bds$" },
  BDT: { "name": "Bangladeshi Taka", "isoCode": "BDT", symbol: "৳" },
  BGN: { "name": "Bulgarian Lev", "isoCode": "BGN", symbol: "лв." },
  BHD: { "name": "Bahraini Dinar", "isoCode": "BHD", symbol: ".د.ب" },
  BIF: { "name": "Burundian Franc", "isoCode": "BIF", symbol: "FBu" },
  BMD: { "name": "Bermudan Dollar", "isoCode": "BMD", symbol: "BD$" },
  BND: { "name": "Brunei Dollar", "isoCode": "BND", symbol: "B$" },
  BOB: { "name": "Bolivian Boliviano", "isoCode": "BOB", symbol: "[]" },
  BRL: { "name": "Brazilian Real", "isoCode": "BRL", symbol: "R$" },
  BSD: { "name": "Bahamian Dollar", "isoCode": "BSD", symbol: "B$" },
  BTC: { "name": "Bitcoin", "isoCode": "BTC", symbol: "฿" },
  BTN: { "name": "Bhutanese Ngultrum", "isoCode": "BTN", symbol: "Ch." },

  BWP: { "name": "Botswanan Pula", "isoCode": "BWP", symbol: "P" },
  BYN: { "name": "Belarusian Ruble", "isoCode": "BYN", symbol: "Br" },
  BZD: { "name": "Belize Dollar", "isoCode": "BZD", symbol: "BZ$" },
  CAD: { "name": "Canadian Dollar", "isoCode": "CAD", symbol: "CA$" },
  CDF: { "name": "Congolese Franc", "isoCode": "CDF", symbol: "CF" },
  CHF: { "name": "Swiss Franc", "isoCode": "CHF", symbol: "SFr" },
  CLF: { "name": "Chilean Unit of Account (UF)", "isoCode": "CLF", symbol: "[]" },
  CLP: { "name": "Chilean Peso", "isoCode": "CLP", symbol: "CLP$" },
  CNH: { "name": "Chinese Yuan (Offshore)", "isoCode": "CNH", symbol: "¥" },
  CNY: { "name": "Chinese Yuan", "isoCode": "CNY", symbol: "¥" },
  COP: { "name": "Colombian Peso", "isoCode": "COP", symbol: "COP$" },
  CRC: { "name": "Costa Rican Colón", "isoCode": "CRC", symbol: "₡" },
  CUC: { "name": "Cuban Convertible Peso", "isoCode": "CUC", symbol: "CUC$" },
  CUP: { "name": "Cuban Peso", "isoCode": "CUP", symbol: "$MN" },
  CVE: { "name": "Cape Verdean Escudo", "isoCode": "CVE", symbol: "Esc" },
  CZK: { "name": "Czech Republic Koruna", "isoCode": "CZK", symbol: "Kč" },
  DJF: { "name": "Djiboutian Franc", "isoCode": "DJF", symbol: "Fdj" },
  DKK: { "name": "Danish Krone", "isoCode": "DKK", symbol: "kr." },
  DOP: { "name": "Dominican Peso", "isoCode": "DOP", symbol: "RD$" },
  DZD: { "name": "Algerian Dinar", "isoCode": "DZD", symbol: "دج" },
  EGP: { "name": "Egyptian Pound", "isoCode": "EGP", symbol: "E£" },
  ERN: { "name": "Eritrean Nakfa", "isoCode": "ERN", symbol: "Nfk" },
  ETB: { "name": "Ethiopian Birr", "isoCode": "ETB", symbol: "pt" },

  // EUR: { "name": "Euro", "isoCode": "EUR", symbol: "£" },
  FJD: { "name": "Fijian Dollar", "isoCode": "FJD", symbol: "FJ$" },
  FKP: { "name": "Falkland Islands Pound", "isoCode": "FKP", symbol: "£" },
  // GBP: { "name": "British Pound Sterling", "isoCode": "GBP", symbol: "£" },
  GEL: { "name": "Georgian Lari", "isoCode": "GEL", symbol: "₾" },
  GGP: { "name": "Guernsey Pound", "isoCode": "GGP", symbol: "£" },
  GHS: { "name": "Ghanaian Cedi", "isoCode": "GHS", symbol: "GH₵" },
  GIP: { "name": "Gibraltar Pound", "isoCode": "GIP", symbol: "£" },
  GMD: { "name": "Gambian Dalasi", "isoCode": "GMD", symbol: "D" },

  GNF: { "name": "Guinean Franc", "isoCode": "GNF", symbol: "FG" },
  GTQ: { "name": "Guatemalan Quetzal", "isoCode": "GTQ", symbol: "Q" },
  GYD: { "name": "Guyanaese Dollar", "isoCode": "GYD", symbol: "G$" },
  HKD: { "name": "Hong Kong Dollar", "isoCode": "HKD", symbol: "HK$" },
  HNL: { "name": "Honduran Lempira", "isoCode": "HNL", symbol: "L" },
  HRK: { "name": "Croatian Kuna", "isoCode": "HRK", symbol: "kn" },
  HTG: { "name": "Haitian Gourde", "isoCode": "HTG", symbol: "G" },
  HUF: { "name": "Hungarian Forint", "isoCode": "HUF", symbol: "Ft" },
  IDR: { "name": "Indonesian Rupiah", "isoCode": "IDR", symbol: "Rp" },
  ILS: { "name": "Israeli New Sheqel", "isoCode": "ILS", symbol: "₪" },
  IMP: { "name": "Manx pound", "isoCode": "IMP", symbol: "£" },
  INR: { "name": "Indian Rupee", "isoCode": "INR", symbol: "₹" },
  IQD: { "name": "Iraqi Dinar", "isoCode": "IQD", symbol: "د.ع" },
  IRR: { "name": "Iranian Rial", "isoCode": "IRR", symbol: "﷼" },
  ISK: { "name": "Icelandic Króna", "isoCode": "ISK", symbol: "kr" },
  JEP: { "name": "Jersey Pound", "isoCode": "JEP", symbol: "£" },
  JMD: { "name": "Jamaican Dollar", "isoCode": "JMD", symbol: "J$" },
  JOD: { "name": "Jordanian Dinar", "isoCode": "JOD", symbol: "JD" },
  JPY: { "name": "Japanese Yen", "isoCode": "JPY", symbol: "¥" },
  KES: { "name": "Kenyan Shilling", "isoCode": "KES", symbol: "Ksh" },
  KGS: { "name": "Kyrgystani Som", "isoCode": "KGS", symbol: "сом" },
  KHR: { "name": "Cambodian Riel", "isoCode": "KHR", symbol: "៛" },
  KMF: { "name": "Comorian Franc", "isoCode": "KMF", symbol: "CF" },
  KPW: { "name": "North Korean Won", "isoCode": "KPW", symbol: "₩" },
  KRW: { "name": "South Korean Won", "isoCode": "KRW", symbol: "₩" },
  KWD: { "name": "Kuwaiti Dinar", "isoCode": "KWD", symbol: "د.ك" },

  KYD: { "name": "Cayman Islands Dollar", "isoCode": "KYD", symbol: "CI$" },
  KZT: { "name": "Kazakhstani Tenge", "isoCode": "KZT", symbol: "₸" },
  LAK: { "name": "Laotian Kip", "isoCode": "LAK", symbol: "₭N" },
  LBP: { "name": "Lebanese Pound", "isoCode": "LBP", symbol: "LL" },
  LKR: { "name": "Sri Lankan Rupee", "isoCode": "LKR", symbol: "₨" },
  LRD: { "name": "Liberian Dollar", "isoCode": "LRD", symbol: "L$" },
  LSL: { "name": "Lesotho Loti", "isoCode": "LSL", symbol: "L" },

  LYD: { "name": "Libyan Dinar", "isoCode": "LYD", symbol: "ل.د" },
  MAD: { "name": "Moroccan Dirham", "isoCode": "MAD", symbol: ".م." },
  MDL: { "name": "Moldovan Leu", "isoCode": "MDL", symbol: "L" },
  MGA: { "name": "Malagasy Ariary", "isoCode": "MGA", symbol: "Ar" },
  MKD: { "name": "Macedonian Denar", "isoCode": "MKD", symbol: "ден" },
  MMK: { "name": "Myanma Kyat", "isoCode": "MMK", symbol: "K" },
  MNT: { "name": "Mongolian Tugrik", "isoCode": "MNT", symbol: "₮" },
  MOP: { "name": "Macanese Pataca", "isoCode": "MOP", symbol: "MOP$" },
  MRO: { "name": "Mauritanian Ouguiya (pre-2018)", "isoCode": "MRO", symbol: "UM" },
  MRU: { "name": "Mauritanian Ouguiya", "isoCode": "MRU", symbol: "UM" },
  MUR: { "name": "Mauritian Rupee", "isoCode": "MUR", symbol: "₨" },

  MVR: { "name": "Maldivian Rufiyaa", "isoCode": "MVR", symbol: "Rf." },
  MWK: { "name": "Malawian Kwacha", "isoCode": "MWK", symbol: "K" },
  MXN: { "name": "Mexican Peso", "isoCode": "MXN", symbol: "Mex$" },
  MYR: { "name": "Malaysian Ringgit", "isoCode": "MYR", symbol: "RM" },
  MZN: { "name": "Mozambican Metical", "isoCode": "MZN", symbol: "MT" },
  NAD: { "name": "Namibian Dollar", "isoCode": "NAD", symbol: "N$" },
  NGN: { "name": "Nigerian Naira", "isoCode": "NGN", symbol: "₦" },
  NIO: { "name": "Nicaraguan Córdoba", "isoCode": "NIO", symbol: "C$" },

  NOK: { "name": "Norwegian Krone", "isoCode": "NOK", symbol: "kr" },
  NPR: { "name": "Nepalese Rupee", "isoCode": "NPR", symbol: "₨" },
  NZD: { "name": "New Zealand Dollar", "isoCode": "NZD", symbol: "NZ$" },
  OMR: { "name": "Omani Rial", "isoCode": "OMR", symbol: "ع." },
  PAB: { "name": "Panamanian Balboa", "isoCode": "PAB", symbol: "B/." },
  PEN: { "name": "Peruvian Nuevo Sol", "isoCode": "PEN", symbol: "S/" },
  PGK: { "name": "Papua New Guinean Kina", "isoCode": "PGK", symbol: "K" },
  PHP: { "name": "Philippine Peso", "isoCode": "PHP", symbol: "₱" },

  PKR: { "name": "Pakistani Rupee", "isoCode": "PKR", symbol: "₨" },
  PLN: { "name": "Polish Zloty", "isoCode": "PLN", symbol: "zł" },
  PYG: { "name": "Paraguayan Guarani", "isoCode": "PYG", symbol: "₲" },
  QAR: { "name": "Qatari Rial", "isoCode": "QAR", symbol: "ر.ق" },
  RON: { "name": "Romanian Leu", "isoCode": "RON", symbol: "lei" },
  RSD: { "name": "Serbian Dinar", "isoCode": "RSD", symbol: "дин" },
  RUB: { "name": "Russian Ruble", "isoCode": "RUB", symbol: "₽" },
  RWF: { "name": "Rwandan Franc", "isoCode": "RWF", symbol: "FRw" },
  SAR: { "name": "Saudi Riyal", "isoCode": "SAR", symbol: "ر.س" },
  SBD: { "name": "Solomon Islands Dollar", "isoCode": "SBD", symbol: "SI$" },

  SCR: { "name": "Seychellois Rupee", "isoCode": "SCR", symbol: "SRe" },
  SDG: { "name": "Sudanese Pound", "isoCode": "SDG", symbol: "£" },
  SEK: { "name": "Swedish Krona", "isoCode": "SEK", symbol: "kr" },
  SGD: { "name": "Singapore Dollar", "isoCode": "SGD", symbol: "S$" },
  SHP: { "name": "Saint Helena Pound", "isoCode": "SHP", symbol: "£" },
  SLL: { "name": "Sierra Leonean Leone", "isoCode": "SLL", symbol: "Le" },
  SOS: { "name": "Somali Shilling", "isoCode": "SOS", symbol: "Sh.So." },
  SRD: { "name": "Surinamese Dollar", "isoCode": "SRD", symbol: "SRD" },

  SSP: { "name": "South Sudanese Pound", "isoCode": "SSP", symbol: "£" },
  STD: {
    "name": "São Tomé and Príncipe Dobra (pre-2018)",
    "isoCode": "STD"
 , symbol: "£" },
  STN: { "name": "São Tomé and Príncipe Dobra", "isoCode": "STN", symbol: "Db" },
  SVC: { "name": "Salvadoran Colón", "isoCode": "SVC", symbol: "₡" },
  SYP: { "name": "Syrian Pound", "isoCode": "SYP", symbol: "LS" },
  SZL: { "name": "Swazi Lilangeni", "isoCode": "SZL", symbol: "L" },

  THB: { "name": "Thai Baht", "isoCode": "THB", symbol: "฿" },
  TJS: { "name": "Tajikistani Somoni", "isoCode": "TJS", symbol: "[]" },
  TMT: { "name": "Turkmenistani Manat", "isoCode": "TMT", symbol: "[]" },
  TND: { "name": "Tunisian Dinar", "isoCode": "TND", symbol: "د.ت" },
  TOP: { "name": "Tongan Pa'anga", "isoCode": "TOP", symbol: "T$" },
  TRY: { "name": "Turkish Lira", "isoCode": "TRY", symbol: "₺" },
  TTD: { "name": "Trinidad and Tobago Dollar", "isoCode": "TTD", symbol: "TT$" },
  TWD: { "name": "New Taiwan Dollar", "isoCode": "TWD", symbol: "NT$" },
  TZS: { "name": "Tanzanian Shilling", "isoCode": "TZS", symbol: "Tsh" },

  UAH: { "name": "Ukrainian Hryvnia", "isoCode": "UAH", symbol: "₴" },
  UGX: { "name": "Ugandan Shilling", "isoCode": "UGX", symbol: "USh" },
  // USD: { "name": "United States Dollar", "isoCode": "USD", symbol: "£" },
  UYU: { "name": "Uruguayan Peso", "isoCode": "UYU", symbol: "$U" },
  UZS: { "name": "Uzbekistan Som", "isoCode": "UZS", symbol: "[]" },
  VEF: { "name": "Venezuelan Bolívar Fuerte (Old)", "isoCode": "VEF", symbol: "Bs.S." },
  VES: { "name": "Venezuelan Bolívar Soberano", "isoCode": "VES", symbol: "Bs.S." },
  VND: { "name": "Vietnamese Dong", "isoCode": "VND", symbol: "₫" },
  VUV: { "name": "Vanuatu Vatu", "isoCode": "VUV", symbol: "VT" },
  
  WST: { "name": "Samoan Tala", "isoCode": "WST", symbol: "£" },
  XAF: { "name": "CFA Franc BEAC", "isoCode": "XAF", symbol: "£" },
  XAG: { "name": "Silver Ounce", "isoCode": "XAG", symbol: "£" },
  XAU: { "name": "Gold Ounce", "isoCode": "XAU", symbol: "£" },
  XCD: { "name": "East Caribbean Dollar", "isoCode": "XCD", symbol: "£" },
  XDR: { "name": "Special Drawing Rights", "isoCode": "XDR", symbol: "£" },
  XOF: { "name": "CFA Franc BCEAO", "isoCode": "XOF", symbol: "£" },
  XPD: { "name": "Palladium Ounce", "isoCode": "XPD", symbol: "£" },
  XPF: { "name": "CFP Franc", "isoCode": "XPF", symbol: "£" },
  XPT: { "name": "Platinum Ounce", "isoCode": "XPT", symbol: "£" },
  YER: { "name": "Yemeni Rial", "isoCode": "YER", symbol: "£" },
  ZAR: { "name": "South African Rand", "isoCode": "ZAR", symbol: "R" },
  ZMW: { "name": "Zambian Kwacha", "isoCode": "ZMW", symbol: "£" },
  ZWL: { "name": "Zimbabwean Dollar", "isoCode": "ZWL", symbol: "£" }

  // AUD: { isoCode: "AUD", symbol: "$", name: "Australian Dollar", symbol: "£" },
  // BGN: { isoCode: "BGN", symbol: "лв.", name: "Bulgarian Lev", symbol: "£" },
  // BRL: { isoCode: "BRL", symbol: "R$", name: "Brazilian Real", symbol: "£" },
  // CAD: { isoCode: "CAD", symbol: "$", name: "Canadian Dollar", symbol: "£" },
  // CHF: { isoCode: "CHF", symbol: "CHF", name: "Swiss Franc", symbol: "£" },
  // CNY: { isoCode: "CNY", symbol: "¥", name: "Chinese Yuan", symbol: "£" },
  // CZK: { isoCode: "CZK", symbol: "Kč", name: "Czech Koruna", symbol: "£" },
  // DKK: { isoCode: "DKK", symbol: "kr.", name: "Danish Krone", symbol: "£" },
  // HKD: { isoCode: "HKD", symbol: "$", name: "Hong Kong Dollar", symbol: "£" },
  // HRK: { isoCode: "HRK", symbol: "kn", name: "Croatian Kuna", symbol: "£" },
  // HUF: { isoCode: "HUF", symbol: "Ft", name: "Hungarian Forint", symbol: "£" },
  // IDR: { isoCode: "IDR", symbol: "Rp", name: "Indonesian Rupiah", symbol: "£" },
  // ILS: { isoCode: "ILS", symbol: "₪", name: "Israeli New Shekel", symbol: "£" },
  // INR: { isoCode: "INR", symbol: "₹", name: "Indian Rupee", symbol: "£" },
  // ISK: { isoCode: "ISK", symbol: "kr", name: "Icelandic Króna", symbol: "£" },
  // JPY: { isoCode: "JPY", symbol: "¥", name: "Japanese Yen", symbol: "£" },
  // KRW: { isoCode: "KRW", symbol: "₩", name: "South Korean Won", symbol: "£" },
  // MXN: { isoCode: "MXN", symbol: "$", name: "Mexican Peso", symbol: "£" },

  // MYR: { isoCode: "MYR", symbol: "RM", name: "Malaysian Ringgit", symbol: "£" },
  // NOK: { isoCode: "NOK", symbol: "kr", name: "Norwegian Krone", symbol: "£" },
  // NZD: { isoCode: "NZD", symbol: "$", name: "New Zealand Dollar", symbol: "£" },
  // PHP: { isoCode: "PHP", symbol: "₱", name: "Philippine Piso", symbol: "£" },
  // PLN: { isoCode: "PLN", symbol: "zł", name: "Polish Zloty", symbol: "£" },
  // RON: { isoCode: "RON", symbol: "lei", name: "Romanian Leu", symbol: "£" },

  // RUB: { isoCode: "RUB", symbol: "₽", name: "Russian Ruble", symbol: "£" },
  // SEK: { isoCode: "SEK", symbol: "kr", name: "Swedish Krona", symbol: "£" },
  // SGD: { isoCode: "SGD", symbol: "$", name: "Singapore Dollar", symbol: "£" },

  // THB: { isoCode: "THB", symbol: "฿", name: "Thai Baht", symbol: "£" },
  // TRY: { isoCode: "TRY", symbol: "₺", name: "Turkish Lira", symbol: "£" },

  // ZAR: { isoCode: "ZAR", symbol: "R", name: "South African Rand", symbol: "£" }
};
